### ISSUE TITLE
Could not find a version of package millerp/boleto-cloud matching your minimum-stability (stable).

### ISSUE THREAD

**Issue by dv336699** [millerp/boleto-cloud-sdk#7]
Não sei se esta biblioteca ainda está em beta, mas ao tentar instalar não vai, pois as tags que existem estão em beta.

Usando 
```
composer require millerp/boleto-cloud v1.3-beta
```
vai de boa porém.

A propósito, ótimo fonte 👍

**Comment by millerp** [comment]
Fala ai @diego-vieira, beleza?

Acontece que, no seu composer estava configurado para usar uma versão `stable` ou um `Latest release` e no repositório só tinha `Pre-release`. Acredito que tenha sido por causa disso.

**Fiz um novo release, acredito que agora não precise especificar a tag.**

Valeu ai!
